version: 1.3.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(APPVEYOR_REPO_BRANCH):$(APPVEYOR_REPO_COMMIT)
#install:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-nuget-3-3-0.ps1'))
before_build:
  - cmd: |
      setlocal enabledelayedexpansion
      setlocal EnableExtensions
      set NUGET=.nuget\NuGet.exe
      
      %NUGET% restore
      
      REM Set version attributes..
      FOR /R %%F IN (*.nuspec) DO (Tools\UnixUtils\sed.exe -i -e "s|0\.0\.0\.0|%APPVEYOR_BUILD_VERSION%|g" %%F)
      FOR /R %%F IN (*.nuspec) DO (Tools\UnixUtils\sed.exe -i -e "s|GIT_COMMIT|%APPVEYOR_REPO_COMMIT%|g" %%F)
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
before_test:
  - cmd: |
      set PATH=C:\Tools\NUnit3\bin;%PATH%
after_test:
  - ps: |
      #$wc = New-Object 'System.Net.WebClient'
      #$wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
deploy:
  - provider: NuGet
    api_key:
      secure: jc+4BDgVroTlVEi4gmAwF3snBZ1NmUpAXNBNsK3tMLREneY7IMVOZSwJtKOZ3dDl
    on:
      branch: master
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

